use_frameworks!
platform :ios, '10.0'

target 'PluggableApplicationDelegate_Example' do
  pod 'PluggableApplicationDelegate', :path => '../'

  target 'PluggableApplicationDelegate_Tests' do
    inherit! :search_paths

    
  end
end
